language: minimal
services:
  - docker

branches:
  except:
  - "/^flux-*/"

env:
  global:
  - IMAGE_NAME="itsre/securitywiki"
  - COMMIT="${TRAVIS_COMMIT::8}"
  - secure: MemEeq1rcAUozAsnBpF/Ub+2UqNo7jQOWHh2FMQDG8MTyRqGbsgOKrtOjSEAQIYcxmAojtd+HbY6TmnrtLoEbRRzJNZa3a3mRnSI5+zbt1ywhiedhrjv6S+QQa2kVplRhaziYky4WI5lM8mo02+1P/VxKdiegFXIGUcrwg80jmiTstODJo1DodiQLR5SofZOlbeqewKm9fYznFmZ3GqX+LEZQHoonLrBrKJFAlUUFeqy7kDI8qf9IEfTTG9kMiaxjh4nBO6l/QISpOE479tEY5ZIKFhe/+Ma4oL23oFfJ+FiOp8aETTg95egP4eJFjHolwk0ub9eCkStdSRtzQQYxgfcmCwQEMnWlDKZH0wF8ATyaA00pUMK84b8bx0rO84GPSMyMFG9T1hA6wXdQa66cIUtAWxPCWODZTCzLo5z3SRcY0xSweIEi88MiIVfd+wcDG4n1sgITKCXQd6xdG73FZcUS/K7fpFPZedexDzSsftWZNpOP9+3nxtjANZSZ2zqQkqiTX79KtdOrrJn4E+hQIRcN3EsiD5dQ/vjgdLkPlaH63Nb2c6CnVmnZMEEGhfb4zxnfejqPkdlyM+k8FSCzFfXWNKc72k6m6614bnBNGS5gxy/vZhc8KQFn3mjdOOhJ15oMpwDORxYVeXlPOW+avlOjBn2pwhWhRLaiJzUXJQ=
  - secure: iqHMrikyVjdYTJL21XunG/zIAXQLbRo+uUyhQ/Jn7UMv73aSOPrSzs9AOO5UIPEO0XdL9XNj0wVx36pQGIOMv7wIbw504IxN4mQpw/J0U0yel0JZriM04EtDksgS2UIDoZ9UrOenNmzEMgUeQX/VJSM5Z6oJhqoGW0RM/z8cfQoyTcZZG+w7fQgtKamgblOKSNXKJs7U2Gs6VtrNQg/L7o6o62fZyjO+VGPicOWqPlOWQMFCNpCtYUTuaBlTLGtV8hls7YuzsJGBcLbydbSBd+TK8OeKJcOSXMOfeJ+6IftTvwtcYstkp3xs8T9syHIiLNno8rENzz9rSgfSb7zf05cJ2qEY8ndoCk0BclGErvckPd4MqEE20zjncvttgKFIy0h9gkk5eXptxZ5IU1WAdLV9BsheEZGdvTYz4A2FBHllhf2C2NxrermmCZE3Og+mcrxOIrn483+EuiF5zA+Uzb1JxNEoa3MCciD0xWstdITdcG296btE8wAOUlgRmX9w9OGOUFVkoyKZJyAyMlkft6GTWQVzaf8to4gKm2EfQPbRuT7mECSlToWecNVkZpyrhgog/sWrQeGqL0wUUJrdZ2WeX+X6IKYCxyCFJpIsPVDhi2DqLUD60bYGY2hWUe5T8n9Ef1nHJiPH+rXj2DdpDiYWnA9yibNKQmq8iq+db6k=

before_script:
  - SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
  - REVISION_TAG="$SAFE_BRANCH_NAME-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG"; fi
  - echo "Branch $SAFE_BRANCH_NAME"
  - echo "Tag $TRAVIS_TAG"
  - if [ "$TRAVIS_TAG" == "" ]; then docker pull "$IMAGE_NAME:$SYMBOLIC_TAG" || true; fi

after_script:
  - docker images

script:
  - docker build --tag "$IMAGE_NAME" --tag "$IMAGE_NAME:$COMMIT" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$REVISION_TAG"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$SYMBOLIC_TAG"

deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
  script:
    - docker push "$IMAGE_NAME:$REVISION_TAG" && docker push "$IMAGE_NAME:$SYMBOLIC_TAG"
