language: minimal
services:
  - docker

branches:
  except:
  - "/^flux-*/"

env:
  global:
  - IMAGE_NAME="itsre/securitywiki"
  - COMMIT="${TRAVIS_COMMIT::8}"
  - secure: "oD29q59wZOMa+SvGr6a+YJb4sCc1l9KKwZqqgsgGOvHj4ldJiTra0fcvqbVdTnkqBmwrnPgqBY8MpplwxVrg13sgaOfstM9wqymD1XznqYDLJbZPNgqtHJe5JfPLCmkaPubJmruWzDglIyerQdM7+BtWdT5VYSLQf1tI/liOpB0pJfEDQ6g+UeAHuNVx5+Ni2DdFSPR4snCiChQzSWG2rfzkNfFwWC0q5xRPsR49sv6RHf4IGH3zO4qP5qU9UA849lwg4cLTuFxMMZ8hiKOmScYKUtK/iYOYF7/7LAJqaRlW58GTPk9nWZ9ydyKNyXN5+qwkGAwQe8i3HRI+FaQmMTtFCyZie7bBypylY4n0VQJZ3KC8WZ3E565w7DrM4xvMfZUwE9Rxqpa5DLv9WzGqWhbmiGT0ed3kqy6T11AL3ykHuhTneN13mUvxDcFT1xlHjvhjN212U05qMq50KoMbIeWsatCIlVW7vywPFDkTdGFKkXNKpB30jiUAlnneY7sNGq/E+s6q8iX0wlFr4V9m6Kl3gGOIpYiQ9UwutaWYrp6hRagEfCJ8jh7oR3/AUw7hzAxzND10fUQxPfVG0Uftz3iDRZyd+mu06ztszQlnQoH5/NX852FuNRdffGXltP9mpuuJsHdVol9ei/EoJZNcRtcMsWcFhiU0uo/vBgwu50s="
  - secure: "YXIqbngKuly5w76DNhsndAm3M/6GvYPYMVTvI89Uml3jhUuF4f9r5gWHrWTSEof5GnkVklYnGGCMTMfl/oT2J9SLOJp4vg4MMt94q5gFBJT9gfvt2xQ3JaDXhrYORT9Q06U6gLgJzLkNA9MbXVcp8zzoKD2BwvP/VaT4aVzwFdRzQzwWQoUuxHsjlkGpiD7FuvPEzkDcE3O/NUU+FpdlrMi1vPHHD+eUZ04n8Fl2acHEjDc2E9WVywOuTF2fTZ38F3xFn0CEk9E7AzHefyOUupDHVsD8pHOER7hArGOeB4XMuLh7LSzFbvAI8MMraoBpgV+izy6uIXbpQLEQ29z0nXrNRVlWVCYwgxFJmMojKVPdumDEBYbXybZdZXv/DCvlVNs5K6Q5OwQ1lOrWULgGGgY8i5Eh8jf8L5T5uWCFmLZfC6mj673R0PZOPNbK01tddgVQ2iXYAGvKV4w8+GsEg+jtB5rYevjK4TaWrcTup5d1KGjdZkWntXVLbVsR7Xk8OygwQgScpOdScEjUfvS624fxowIE5THEAIpabu4qYeNZqs2oBtFRLlJp05xg8bz0uwCnXBa8wmrjAyPIVCMC0bEmFyWlYJnaSCbgrscsCjtD1l0Hgumi1gn9bEZ6xyZku10h9ES29tfbrmqQqeboZHkCs3EPFfT/6n6dfyr2DPU="

before_script:
  - SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
  - REVISION_TAG="$SAFE_BRANCH_NAME-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG"; fi
  - echo "Branch $SAFE_BRANCH_NAME"
  - echo "Tag $TRAVIS_TAG"
  - if [ "$TRAVIS_TAG" == "" ]; then docker pull "$IMAGE_NAME:$SYMBOLIC_TAG" || true; fi

after_script:
  - docker images

script:
  - docker build --tag "$IMAGE_NAME" --tag "$IMAGE_NAME:$COMMIT" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$REVISION_TAG"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$SYMBOLIC_TAG"

deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
  script:
    - docker push "$IMAGE_NAME:$REVISION_TAG" && docker push "$IMAGE_NAME:$SYMBOLIC_TAG"
