language: minimal
services:
  - docker

branches:
  except:
  - "/^flux-*/"
env:
  global:
  - IMAGE_NAME="itsre/securitywiki"
  - COMMIT="${TRAVIS_COMMIT::8}"
  - secure: "wQjEvLjoBODgnNJ36rU+mOJr1/jZo4q7lI72LCnRihorq016UIMF/Oy9Qdb18EYf4NzpNw1BOfjYPDy29By0ttJoG46L9RFa0uFW5m18+jPFWpWtz40HCh3Lsg2Mn3kUzhHS58N7J6KMx6To08mU6EXV2AvyuQrXTWfGTXwowL+nA16elhCT5Z8a4weuBH14m+qCMkQ+Rk+/JOMoN7RmOxLWHBIzXD+xb/MOJwHo/GsLkz54JfkVQZ/CcdmHpQx4gbboJahxpUAocN9WHv1T9sjMYuK0hurcRnPnU7ovC097eJapKJn6zKCG3fhuuOLwHmxJ8NpYZ1OSBoXrrXC8z3aMe+GneRGJ0HHReSKmUbt06grrrAPkiad7CfDl9Gh0T+z0wcfktUBNn6ZX+FAbshtJ0CV80pregbmIHUWLAqqQ+dWYv8CPxqYJ7iyEqKa/RxccB8rEioImx4tTjaCN20/n8TU4NUd0fWCjLCoddZ4Qmvu1eHPPU6i/gVqxRRKRKaxpNxcz5OCq0dRz7810m1TwWoR6mqeTMhwysSO5CGn9Q50rmNA+64UdF7htMDJrtrWfR0p0eyuQU90IFwDruie/48JRMvuhwMjAFNQ1g8ACdmjME0yvVlL8cpXt92nI7nBMiwtsy/m66kxYr6B451yO658/Zys1cJcHkUQSaA0="
  - secure: "tAZ5x9eyPnoDTCW9ajuywKk59PK4OybFgd5dGUENpowC2aR5X5yowTo6N8mTL49+Ng4uYXoGU+EZ/IjoGLlsTAlwCR1Skwji4aro2wSyF51hFGxKp9PJr/g7NplJNhfqbK1WTApS5ZhSa1yKlur0cBUzffop4qB07PCvkcdPEqmhME0/BHlsIQiWj5MsCocFAuHLILb08ErKdwAFOWVAqMZ2QyqaRHiwd9dBzpcMTVLLn3M6Luz2EDcCfFGfriX6I/3H5tyOg9+h3Kv/tChxF8sMs/Pfe1FiJEFuU95AHAJ1oanYZ4gmaQH/DloPw+KTIN1dJ1T+i0Ng6lJkOREt4O4e8L8xvGTqLN9d84k78voG3Q4rXzl7A34uetRMmS2fSkpqWvts5WCBDiFIfXX+N5P7nBKrf+V6pJMYXjEiD2BWuvhwj9BZXdbNPN7TvyvDxfEabtixYMR3LPdF4r12L/d0SRmDK77NoefzghSZszmD8sVyOOnhrUrM79RUFA1Bm5HPVWRF3Zu9V1GMtbG6M794Z59eCmPYhEchRCS+mMm67o7BkX0JTiWsLptytPWekOgXUf9YP7T4MAKulmJ6L0Poz1lKzZPM9wWo00VjKLRJoDOn3r2SAQGaEE8r/azJKsf3D0flAtlTgqFTBwv7ElJcJCdUucOedKxVAmW24Kg="

before_script:
  - SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
  - REVISION_TAG="$SAFE_BRANCH_NAME-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG"; fi
  - echo "Branch $SAFE_BRANCH_NAME"
  - echo "Tag $TRAVIS_TAG"
  - if [ "$TRAVIS_TAG" == "" ]; then docker pull "$IMAGE_NAME:$SYMBOLIC_TAG" || true; fi

after_script:
  - docker images

script:
  - docker build --tag "$IMAGE_NAME" --tag "$IMAGE_NAME:$COMMIT" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$REVISION_TAG"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$SYMBOLIC_TAG"

deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
  script:
    - docker push "$IMAGE_NAME:$REVISION_TAG" && docker push "$IMAGE_NAME:$SYMBOLIC_TAG"
