language: python
services:
- docker
branches:
  except:
  - "/^flux-*/"
before_deploy:
- eval $(aws ecr get-login --no-include-email --region us-west-2)
- docker tag $ECR "$ECR:$REVISION_TAG"
- docker tag $ECR "$ECR:$SYMBOLIC_TAG"
before_script:
- SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
- REVISION_TAG="$SAFE_BRANCH_NAME-$TRAVIS_COMMIT"
- if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG";
  fi
- echo "Branch $SAFE_BRANCH_NAME"
- echo "Tag $TRAVIS_TAG"
- if [ "$TRAVIS_TAG" == "" ]; then docker pull "$ECR:$SYMBOLIC_TAG" || true; fi
after_script:
- docker images
script:
- pip install awscli
- docker build --tag "$ECR" --tag "$ECR:$COMMIT" .
deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
  script:
  - docker push "$ECR:$REVISION_TAG" && docker push "$ECR:$SYMBOLIC_TAG"
env:
  global:
  - secure: WMjdUMseyXBk+84Ei/AsJCgE9/H68vmviKpV1ziTFq3H8XnVvq3po0rZMJPCFqRnMgVRIkdWvwU0kUdi/IgWk53DPE1wH3X7QPUtX7r2sbrfbvPqM8VZkTZnW8KU1QLCOKeWS1zqDHK9jxx1wz1mjBwxAoyvh16RUH9NecrXRM/Gk5Yfs1oYbgq7Yi8lpzUxyAS0f19JKv09R4vIZIf3+As49zoHS/FlIKd5C0pF/c67NVisajC34TUFOIb2S8q8h8UQ0JvsAvmVoVora6QF9iN5HkkNb5UMaQVDgOMXeYr/HjQ/+epy/GSQuj2p6Lsrt3Eo6D2A2wg5Qn6kDzP4sdrFr5TqD0G2aIRhicdz2tS6oOLDWcLpqd1uH2+cY2zknIXMlgBbal+ujkqoaOTnSayEZlhz8FQfNyRFhVfcIRtVVLqsw0vE5sU3hnL/3gLCUuhq9Vh0v22KqYiy51rvJ45vWvxTQZGNcpZDkH4B7zexX3cz4ZdX8bT1X6f8LhwlNircQggV0PvlUjRYWXYz/bTzVKtJv8k43omGIvp6M4ZXmMCc6Iv61u7zTNNGyoz/+Fas094fgQT1s8kEhbg/+cDPviJEySSzd+jIxVnzO0RBXpLaYusnWVzJ4TWWujPMUbqXSSTyZb+g4KwzcrXOA7mEKgd4PxuYQ6MRvYHLzzA=
  - secure: OSmwhs5Hr3mkMn8tR2vACF6qOs6dHboHIGrgp3sV/UyRivO0dTyyVo+Ahq7KlX3LabRarP5DEMGb+wGiCPmXtMYGozbztkb2p4/dT0BJkkQapxa1xpwZr+xPCm3nuCJSQJsjglZNdaVZKXTSdlhJGUXM8nrCAPCvBmwH5VWLOhizUp2LF9TmGsEfNcnvrXV8MSy6609o8KhEQx+hYgFpItSZrclqtIPc2w922TCVraIjsP/1ofjj2333+DoHBufkyYRreWpEmysBR9Lgkt+jjw7sLsN92V5XV3Pj0LfmnOv3wN4yoImmzm1VNx7B9oOzyvHdnrAZ8zksddxRCr29tEgwIsT945bwauNdPALNGWfN13XEDGjKP/cj/A2UG2JZ6AWML29LT4Dxuj6SBM/nJGO8P3ds5WO6X5UudrPdWxVpxgTtLknxqQAEkjhXz4paje6hq74/2GoNV4oc9MSPX8ulbb/Gbs02gJPs/h+ZT2vsxIdmu8sfHFZwozpJ80MZYG9sWhmU/cBEHfZ9pLITFU/slk5nq3L+6Gw3qJqMOOXbksto5y6ZEE/xbtrB283n0MfdWehCmhvAzExOY+jPtAQheCi9TtyCTsuJYVUW/yGUOOsFU9KZrAuEmLdXumxgv287JpE3x22ALhOR2uFdG9D0++8FA2ByeuT2yQfdMjY=
  - secure: SvFP0BDTOYU8fHdLvUVEVkIEf5MT/j7Qs2gSE+jgBbnA1+FFuezbEyE4mUg4AIjCNPlNQpqOZN/dzZLcHi6dyNwbZMw5efgs+RtmoyTrAbMsbmMkHgFDNjVhwHXMQUj0ghcvLw/g/J37syIXB5379uOn6ORjdG5oBo+vmUMb9E6gt5+jqPJD08e8T/sf4uldmDvbKBt3c3yExJLw3L41X52MkLi1eCtqp267PUQ1Z2j5bH9nsDwEQ99/0aW6vgNbAx3og2GgzdirMCR8MmAEDPSycQR6hsPkKcTJHjD0ZuqCHFKBgbicjn8/NmZdsTnSRC9PQJM3LmkUc9WQottbNNXD90yvENsGVMwBI6is04Uj2bosM0i/Tga2X6KxsyBiMHZdI691lX2JKqeyo6RCEy3ZO+LOO+SZpwU6KqqHLlA4ZFnjCNLLQ2I4NVUaLG0MK2QyO+D1WjzVDm/5pKOPpxVkvnrw7HlVcqAJb3rTX8tgPdCJmEpqZTD13Q8KV25coDthZQV7GV4emJ3Wq0UEc0GBfA4Z8IMEgOrVQSYp7Ss/G7Q4AvSkACMRWb5kBbgh1hlVZnfPEnMYSW22mS3cxy6GJ8Rb2Y1jEFWdnWq02pumWrYMOSQ9c2c4cathHV57QB3KjmBXV5XucMs6UABjKpPTmRssioFGDQoqhRLffl4=
  - COMMIT="${TRAVIS_COMMIT::8}"
  - ECR="$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/securitywiki"
