language: minimal
services:
  - docker

branches:
  except:
  - "/^flux-*/"

env:
  global:
  - IMAGE_NAME="itsre/securitywiki"
  - COMMIT="${TRAVIS_COMMIT::8}"
  - secure: D4cKdI/hvQwXb6cj/plBOxjJvPHLTWgxTwBbCE9CsADoUpl2nq9//OJUmuIHb6MBOY/D5RWP2BwjWtlbkfpKDPTFEFU4m0juyi2KkhADnVFMWfF7h9aBvd2km+Erw1naq8drG7+dhIb/hBv32Y1AmbcGbkGBqIidRJGD5R5wnhKm4RABqzDb/ID3SglEcXMWqwBbkMqb4+b7btK3tbEMgm8Wjzfwf4xuvo//ulG+opG8RlR3Y1TiishvADVgVHfnYNFOifHphrriYJ4kluNXOumk/Tsi+9geNl6VBIR/s1XohmDauzvfE0l1Gh9oUm4eEnYC+aHxc8Qy9P26jxBH2YYovaBEi3Neppd4c1ShDhtwMnC3sPAakFAK7+e73/VT2Svq1dtE7aygfFbaOJz4jLcZJudQm9ayffeacMQbcfgzyrLLrGLdvTkkg1V7mwIMaJAhD4z5qu3VbpAlkRDWc7hAjRc1BKkhElfrfJ3ooeg9vkwaxj2ohfTLs6EpXsZaCNPq0gxwk2LxsSqaCO7qtdT7NN1pnwgMgE1oUZQ6EK2XGz9gHlwiDuzplVk5DMUmusXpEvv8W2Jj8UytqZzHSpGu8HisCsOY1a4EhukOTH/H4xLn3RrzmH7EnHvyNr0974X+ljOCYOZoaipyN5jeBaVT1so+D2qpsYl8OA+TsxE=
  - secure: YpQTW8AB3WmdllvIzm1KBHWtdAoNkRd/kuLVZ+nFExVMjHjBJWaDkNeJO8eHcBmbHyHXQb7FkDtB/GJ0VooUvOivN4F0unHEXwoigC+D/uqswoQZN5qt1avbPMR8Q+tAmzbNEgRKa/Aip12go3QX/UtFd7sS14kcuU2+DU5AplolYCsO3xK2Vl3E/1mMpjIs98bgtdQ4crahuUpX9ejzW8IbuIAftl664NvpDpCKNlTFK9HvfcKqJgBjIWe3DVP0Av5AgsJ/uwREF0MsdeeV1z5gvSRdfvQGPd1AHfLtYAx0k3iAfehkL3CVQxR+3Q3p5RPlNw5Do0OhysfxelbRwVjWooRJJcICfcvP0JRsexK6AwZGO77K627S5vY7hIFy5RICw7b/m5SeMhFNy+2l3/hLvUr4KJ9+Nkp4deN2Fi2fDH0umLuC8xYeea8GDf2wy1HI3ZEZlkEtRp0A8sREfsChLTkZt0t3oQO3iyGrsGS0Qf7Caxjr/boCOMkOcPl+fyxglgPqrdSsGEbwG31Pgituk7/MNSXKIMGW1ND/V0F6bwkGB9FN97e5k/D/0wLlTfoddZphF5T+aSzZnCwwCbG2RtkVw2nIluCSof1gmIqbgC2uj0ZC7TjHEm7jGGIG/mpo24z6SPZdLve8oT1s0W6efOHL8UudRnpyK90CWvk=

before_script:
  - SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
  - REVISION_TAG="$SAFE_BRANCH_NAME-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG"; fi
  - echo "Branch $SAFE_BRANCH_NAME"
  - echo "Tag $TRAVIS_TAG"
  - if [ "$TRAVIS_TAG" == "" ]; then docker pull "$IMAGE_NAME:$SYMBOLIC_TAG" || true; fi

after_script:
  - docker images

script:
  - docker build --tag "$IMAGE_NAME" --tag "$IMAGE_NAME:$COMMIT" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$REVISION_TAG"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$SYMBOLIC_TAG"

deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
  script:
    - docker push "$IMAGE_NAME:$REVISION_TAG" && docker push "$IMAGE_NAME:$SYMBOLIC_TAG"
