language: minimal
services:
  - docker

branches:
  except:
  - "/^flux-*/"

env:
  global:
    - IMAGE_NAME="itsre/securitywiki"
    - COMMIT="${TRAVIS_COMMIT::8}"
    - secure: "ioZMA4xhqNQIHl4bea1J68EqWt4vd/w+2F3d8YHAq7TqOC0TxPnKxJOD33Mt3e3hkWdj9mJX7kZ3nvHF0wwwdKo8xNzvVVvUWYsDarNJCsPPAtRpZsLCRTYT+5jU75nxsT3XeM2w225LS1R41yE1Ty+tI9NfrXAMh7dPiYFkDOTzkhG7ENO0e/y88sz22uGWSqPKOzzX68miRRGtax4zz7PlBkhcGP9cBuNbcqJm6qSQWzCWwe7wJ74PoXzDvS7c+ht1uACXZJ1dOdW7QW7r0zCRfb+OhpnMXZgZgorxlWH+oTPwLGn3wuetcMZH6i6uNVcSy+HUzjVOey+G7qicuPxoAYW6NQhkKM0EHNlRm7i2v/6kJfdrnCGwDaULBNJNFLkvYCAoEN3AU4q/DM7J40rIP5Td01tSYuk4GKSVZOCPRKFlt5ULxOeJa/6JuIaVZa9ktiaIxy7/+H8q4d1EP3zPOsBVB8RlKIQrPVGO0+CSGrmv1B1D/NQ4NfQidAa+dwXMpp+azUe0Awfbyu1Jn/j5UAAnVqwyg2F04x5ModK2FpTUdvJYDobzmUWiIGaXRrYntTTbaMLQAK3MO1W1r33Vsyg8lxT8v58LTQ2lOne3MBcTddTdCK6u21NDovW+jnrpHqgurfn6t3ysyOzg213ZQuFuN3BMOtI8SlkZXcc="
    - secure: "OWnxiGaIHov/dUkIDD5kF2ZbCPdzU6E2+H86Ck3zf32kHNaS3OOZ9o3vGYds4J+0qdRqbIaD1So0CULX/dRA8Er74vCfbdHUy3vRr92rRHl3xgjrKNPagLu0tkjEtcFxoudcP4IQqsWy70grRzbOvi0LPRSAq4q8NTJPvaTpolr6FB7pRWfszxTnIFJA+8i9SCRNvUshM/toKzC1Pcr/t8tAgtnkq2aosVgRvFwe/go5ZuY2UJ6b+yDGn+e+iT8oZzLyxqG+kWnxyVJSooMIXs7v1d8XiW+Hy1Dd46tSt0V/BTMYOpCBWWDTe2SJqvYXH0zvF99B9wE/gbftQk7rUF59Fu0Zdjpje8LIOISnSaQoXfrWSZZ8q19jVJ786tHhGuV+liW/iUn88tC4Oq7+CjuWxLqCIvENyZCBGghDr9Sa0JFvRlJUy5co9G7SiH8e8iMvOrW4ShZhLEdx0NhyDsgNjwWT1ZI+UzDSmc6/0Kj53nQtPcbWfoeSLJrU4VCEBnyTS5g/EXXR17jykxTPOGvrz95T6EqcMxW5uF4c9mven7CAVe3rDZ2HlQJbaaK92qIHahq8DFWY4xCuyr2VhqEMgjQLmcTzlTLG+5WEmrUEtynLZOmyuQw5Z52kq9fkVnnMWf+Y10m7tWmsfwwEOuvh9MQM3icoi6rv6m1jGZ4="

before_script:
  - SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
  - REVISION_TAG="$SAFE_BRANCH_NAME-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG"; fi
  - echo "Branch $SAFE_BRANCH_NAME"
  - echo "Tag $TRAVIS_TAG"
  - if [ "$TRAVIS_TAG" == "" ]; then docker pull "$IMAGE_NAME:$SYMBOLIC_TAG" || true; fi

after_script:
  - docker images

script:
  - docker build --tag "$IMAGE_NAME" --tag "$IMAGE_NAME:$COMMIT" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$REVISION_TAG"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$SYMBOLIC_TAG"

deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
  script:
    - docker push "$IMAGE_NAME:$REVISION_TAG" && docker push "$IMAGE_NAME:$SYMBOLIC_TAG"
