language: minimal
services:
  - docker

branches:
  except:
  - "/^flux-*/"
env:
  global:
  - IMAGE_NAME="itsre/securitywiki"
  - COMMIT="${TRAVIS_COMMIT::8}"
  - secure: OgrNI9MCdqkxCKD0Vm4/5TWDI50ZAdUh5//fVdysyScZOPvtGLAjshPzr31xxU7+ewHXt6GugbgEOprZnmtcJNzztioFI4Xa1zMTvxZN3PJgD9tXfTag/+hCyWl4Ofveg7u8yVRMjIGSbDdFoLo5LzuCFybUrQj6gFYbF4rYdIMhr1uL0rocQpQgb387DtVeecHV19AX/rSbggUmclgWa2Cs6ee29BQeEB9zmWsBQJo7p1udmeuaug36y1l0v/qFdKkWHZjVweA+vFURM9BD0320h+zeFVASO+dBo96szld5uDPlD8UDWtt5tBIxlnYAu+ecXoK1+t0M3Dc41NEjl13v7w82JLEK6UI6kc7V2u470blxcLuUzT2FbgrgBLLZyClP5foe/TzkllRAwrwNrgqmHtJ1aEw/RbYXI7+YI/agOqhGQT5KoFqSz7oSPVBQVslZ8vpyJaS45xMi03xRriZotuz5pIXn9uWdDnvdrPt9Ri0pVMe4dZhvNtMIw7OSYvP1E2MkAMevxSPbedlCE8Hoh3DUWZzVfp7x8ki2SU8s/fwypUlQ4OjRIlCCl9uLlNRkJIwcGXLldvZitrwW9aX7ZdL9GZshfItCnwXZWQyhseZ433iD5tTqJTffD2TR53cwFBNErXUxVf5bbXlDHC+nxL8u6BMDlz7myFC5QoQ=
  - secure: MCTi0SVBp3222NBhsXJYHkMrajrEZiiAzu5re880PxE2teauEk0amUDNQZAGl1bx7MhYONqtbD9YW/ImDklFK/hSF/T8zOKzO39G0BHlcrsYzUJVkMNgImManjwBOL8V4Hh0+PCEEX1SjZ1xGPbRC5OPu5NSuaHcln+obJZsbvoKOFzrccbBpuwO/eOjucxlnN7IwoVteLg+YvoJBy5GIznrUWWylvMsvxPGd+vyhaKsIWfbSuocfwnhM3nZuU8+nKUMNBudtzAmRVhbQN2iugBzBCilGQ68DzAvWKKlySBfKZFg4cFItG/2UH4n/6nxcnRdOOuJdgUjhbHRkOopjDq1Ls+jWYGrr4AoLkvMgdky9po7QB5fk9ykVoyCBnTIeQnykGu1hhjf9Qw5l8hSItCtfb6NYpjE3KIrUabt58yH37Fkrr7WxirPjMjZ1Zu3+YF2d5c0+U9eJ+oNxyUBMPfRZpZ6eA/Re3Nt+mHIyWAE9dwfPGcbKhgGMCqILToXgMW2sEwe5weSOIq946oS4iW2A365h6tT4sDo8VrogWsJzVgiSGNRxrm2A3QC4UNsHYdshwg7YvJ4PxlzBL1usQopguXk1j/4eoprgrYok98v2lL3Gkav4NAzZ651+xFQsiddlLxTscg3qpANhupCD6RrG72JN84oLi8QX5bBIWA=

before_script:
  - SAFE_BRANCH_NAME=$(echo -n $TRAVIS_BRANCH | perl -pe's/[^a-zA-Z0-9_.-]/_/g' )
  - REVISION_TAG="$SAFE_BRANCH_NAME-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" == "" ]; then SYMBOLIC_TAG="$SAFE_BRANCH_NAME-latest"; else SYMBOLIC_TAG="$TRAVIS_TAG"; fi
  - echo "Branch $SAFE_BRANCH_NAME"
  - echo "Tag $TRAVIS_TAG"
  - if [ "$TRAVIS_TAG" == "" ]; then docker pull "$IMAGE_NAME:$SYMBOLIC_TAG" || true; fi

after_script:
  - docker images

script:
  - docker build --tag "$IMAGE_NAME" --tag "$IMAGE_NAME:$COMMIT" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$REVISION_TAG"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$SYMBOLIC_TAG"

deploy:
  provider: script
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" || $TRAVIS_BRANCH =~ ^(master|prod)$
  script:
    - docker push "$IMAGE_NAME:$REVISION_TAG" && docker push "$IMAGE_NAME:$SYMBOLIC_TAG"
