---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/securitywiki:master-d400ce934c25bc29095e32922d37ec129557fdd3
        name: web
      initContainers:
      - image: itsre/securitywiki:master-d400ce934c25bc29095e32922d37ec129557fdd3
        name: migrate
