---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/securitywiki:master-9f76072d90248bbf3f0ff433408da1520f34e557
        name: web
      initContainers:
      - image: itsre/securitywiki:master-9f76072d90248bbf3f0ff433408da1520f34e557
        name: migrate
