---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/securitywiki:master-91e985bb3d277d20fe073c1f843fec0e0f53485b
        name: web
      initContainers:
      - image: itsre/securitywiki:master-91e985bb3d277d20fe073c1f843fec0e0f53485b
        name: migrate
