---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      containers:
      - image: itsre/securitywiki:master-1649740bdc604d4f42b64d01580b663c817ab3ec
        name: web
