apiVersion: kustomize.config.k8s.io/v1beta1
namespace: securitywiki-prod

bases:
  - ../common

resources:
  - sealedsecret.yaml

patchesStrategicMerge:
- ssl-patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: securitywiki
    path: deployment-patch.yaml

commonLabels:
  environment: prod
