---
apiVersion: v1
kind: Service
metadata:
  name: securitywiki
  labels:
    app: securitywiki
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:783633885093:certificate/741da675-f4fb-4a57-ae8c-cf15382fcd6c
