---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.web: "glob:master-*"
    configmap.reloader.stakater.com/reload: "securitywiki-cm"
