---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  labels:
    app: securitywiki
spec:
  selector:
    matchLabels:
      app: securitywiki
  replicas: 2
  template:
    metadata:
      labels:
        app: securitywiki
    spec:
      containers:
        - name: web
          image: itsre/securitywiki:master-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
              name: securitywiki-https
            - containerPort: 80
              name: securitywiki-http
          resources:
            requests:
              memory: 256Mi
              cpu: "256m"
            limits:
              memory: 512Mi
              cpu: "512m"
          env:
            - name: ENVIRONMENT
              value: stage.unset
            - name: SITE_URL
              value: https://securitywiki.allizom.org.unset
            - name: MYSQL_HOST
              valueFrom:
                configMapRef:
                  name: securitywiki-cm
                  value: database.host
            - name: MYSQL_USER
              valueFrom:
                configMapRef:
                  name: securitywiki-cm
                  value: database.user
            - name: MYSQL_DATABASE
              valueFrom:
                configMapRef:
                  name: securitywiki-cm
                  value: database.name
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: securitywiki-secrets
                  value: database.password
            - name: MEMCACHED_HOST
              valueFrom:
                configMapRef:
                  name: securitywiki-cm
                  value: memcached.host
            - name: MEMCACHED_PORT
              valueFrom:
                configMapRef:
                  name: securitywiki-cm
                  value: memcached.port
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: securitywiki-secrets
                  value: oidc.client_id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: securitywiki-secrets
                  value: oidc.client_secret
            - name: OIDC_CRYPTO_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: securitywiki-secrets
                  value: oidc.crypto_passphrase
