---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  labels:
    app: securitywiki
spec:
  selector:
    matchLabels:
      app: securitywiki
  replicas: 2
  template:
    metadata:
      labels:
        app: securitywiki
    spec:
      volumes:
        - name: securitywiki-fs
          persistentVolumeClaim:
            claimName: securitywiki-shared
      initContainers:
        - name: migrate
          image: itsre/securitywiki:master-latest
          command: [ "/bin/bash", "-c", "chown www-data:www-data /data/securitywiki && find /data/securitywiki \\! -user www-data -exec chown -R www-data:www-data {} \\;" ]
          resources:
            requests:
              memory: 128Mi
              cpu: "128m"
            limits:
              memory: 128Mi
              cpu: "128m"
          volumeMounts:
            - name: securitywiki-fs
              mountPath: /data/securitywiki
      containers:
        - name: web
          image: itsre/securitywiki:master-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
              name: https
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: 256Mi
              cpu: "256m"
            limits:
              memory: 512Mi
              cpu: "512m"
          volumeMounts:
            - name: securitywiki-fs
              mountPath: /data/securitywiki
          env:
            - name: ENVIRONMENT
              value: stage.unset
            - name: SITE_URL
              value: https://securitywiki.allizom.org.unset
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: securitywiki-cm
                  key: database.host
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: securitywiki-cm
                  key: database.user
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: securitywiki-cm
                  key: database.name
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: securitywiki-secrets
                  key: database.password
            - name: MEMCACHED_HOST
              valueFrom:
                configMapKeyRef:
                  name: securitywiki-cm
                  key: memcached.host
            - name: MEMCACHED_PORT
              valueFrom:
                configMapKeyRef:
                  name: securitywiki-cm
                  key: memcached.port
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: securitywiki-secrets
                  key: oidc.client_id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: securitywiki-secrets
                  key: oidc.client_secret
            - name: OIDC_CRYPTO_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: securitywiki-secrets
                  key: oidc.crypto_passphrase
