apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- hpa.yaml
- service.yaml
  #- pvc.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

commonAnnotations:
  team: itsre
  costcenter: "1410"
