---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: securitywiki-shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: ""
  storageClassName: efs

