---
apiVersion: v1
kind: Service
metadata:
  name: securitywiki
  labels:
    app: securitywiki
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: securitywiki
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
    - port: 80
      targetPort: 80
      protocol: TCP

