---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      containers:
      - image: itsre/securitywiki:master-c61509ef9834379207b015430e4f30a5b47df66f
        name: web
