---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/securitywiki:master-e462fa7bb6dd63a49e331120f7e62e5132946782
        name: web
      initContainers:
      - image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/securitywiki:master-e462fa7bb6dd63a49e331120f7e62e5132946782
        name: migrate
