---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/securitywiki:master-80ec141157bca3044b1ee1529a0af1b7b0c12787
        name: web
      initContainers:
      - image: itsre/securitywiki:master-80ec141157bca3044b1ee1529a0af1b7b0c12787
        name: migrate
