---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/securitywiki:master-934b5aa0367f283b72a31e4c74a066a453a5446f
        name: web
      initContainers:
      - image: itsre/securitywiki:master-934b5aa0367f283b72a31e4c74a066a453a5446f
        name: migrate
