---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/securitywiki:master-41866b9337b820541c4bd8cda1b50606162087ed
        name: web
      initContainers:
      - image: itsre/securitywiki:master-41866b9337b820541c4bd8cda1b50606162087ed
        name: migrate
