---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitywiki
  namespace: securitywiki-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/securitywiki:master-b2b59a269c515abf5db998290ce2a88707f5e5b7
        name: web
      initContainers:
      - image: itsre/securitywiki:prod-810f4bd74c0d63e0685c7c77a8d5d76314fb94bc
        name: migrate
