---
apiVersion: v1
kind: Service
metadata:
  name: securitywiki
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:783633885093:certificate/ada4556b-face-4d26-9f0e-129d8eda41f5
